# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitting',
            options={'permissions': ('can_score', 'Can Change Score or mark correct/incorrect')},
        ),
        migrations.RemoveField(
            model_name='progress',
            name='score',
        ),
    ]
