# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20160330_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answers_at_end',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='exam_paper',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='max_questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='random_order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='single_attempt',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(blank=True, help_text='a user friendly url', max_length=60, verbose_name='user friendly url'),
        ),
    ]
