# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(blank=True, help_text='a user friendly url', max_length=60, unique=True, verbose_name='user friendly url'),
        ),
    ]
