# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20160427_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this active?', verbose_name='Is Active'),
        ),
    ]
