# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20160427_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='createdOn',
            field=models.DateField(auto_now=True, default=datetime.date(2016, 4, 27)),
            preserve_default=False,
        ),
    ]
