# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_quiz_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='createdOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
