# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
