# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcquestion',
            name='answer_order',
        ),
    ]
